env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  require-jsdoc: 0
  react/prop-types: 0
  object-curly-spacing:
    - error
    - always
  indent:
    - error
    - 2
